name: Refresh Dashboard Report Data

on:
  schedule:
    - cron: '5 8-17 * * 1-5' # At minute 5 past every hour from 8 through 17 on every day-of-week from Monday through Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install azure-cosmos

      - name: Execute py script # run reports.py
        env:
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
          COSMOS_DB_NAME: ${{ secrets.COSMOS_DB_NAME }}
          COSMOS_DB_URI: ${{ secrets.COSMOS_DB_URI }}
        run: python reports.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated report from database" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master